version: '3'

services:
  client:
    build: client/app
    ports:
      - '3060:3060'
    links:
      - server
    restart: always

  server:
    build: server
    environment:
      SERVER_PORT: 3050
    ports:
      - '3050:3050'
    links:
      - db
    restart: always

  db:
    image: 'mongo'
    restart: always
    expose:
      - 27017
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db