version: '3'
services:
  api:
    build: ./api
    depends_on:
      - db
      - mongo_seed
    networks:
      - webapp
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
      - /app/node_modules
  db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - webapp
  mongo_seed:
    build: ./db
    depends_on:
      - db
    networks:
      - webapp
  ui:
    build: ./ui
    environment:
      - "REACT_APP_EXTERNAL_IP=${EXTERNAL_IP}"
    networks:
      - webapp
    ports:
      - 8080:3000
    volumes:
      - ./ui:/app
      - /app/node_modules
networks:
  webapp:
    driver: bridge
